language: go

os:
  - linux

go:
  - 1.9

sudo: required

services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/docker

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "TokenBalance-$(date +'%Y%m%d%H%M%S')"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "build/tokenbalance-osx-x64"
    - "build/tokenbalance-osx-x32"
    - "build/tokenbalance-linux-x64"
    - "build/tokenbalance-linux-x32"
    - "build/tokenbalance-windows-x64.exe"
    - "build/tokenbalance-windows-x32.exe"
  skip_cleanup: true

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker pull karalabe/xgo-latest

before_script:
  - go get github.com/karalabe/xgo

script:
  - go get -u
  - go test -v
  - ./.travis/build.sh
