language: go

os:
  - linux

go:
  - "1.10.x"

sudo: required

services:
  - docker

env:
  - VERSION=1.51

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - git tag "v$VERSION" --force
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "build/tokenbalance-osx-x64"
    - "build/tokenbalance-osx-x32"
    - "build/tokenbalance-linux-x64"
    - "build/tokenbalance-linux-x32"
    - "build/tokenbalance-linux-arm7"
    - "build/tokenbalance-linux-arm64"
    - "build/tokenbalance-windows-x64.exe"
    - "build/tokenbalance-windows-x32.exe"
  skip_cleanup: true

before_install:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then travis_wait 30 docker pull karalabe/xgo-latest; fi

before_script:
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/rendon/testcli
  - go get github.com/karalabe/xgo

script:
  - go get -u
  - go test -v
  - ./.travis/build.sh
