language: go

os:
  - linux

go:
  - "1.10.x"

sudo: required

services:
  - docker

before_deploy:
  - git config --local user.name "hunterlong"
  - git config --local user.email "info@socialeck.com"
  - make tag

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - "build/tokenbalance-osx-x64.tar.gz"
    - "build/tokenbalance-osx-x32.tar.gz"
    - "build/tokenbalance-linux-x64.tar.gz"
    - "build/tokenbalance-linux-x32.tar.gz"
    - "build/tokenbalance-linux-arm7.tar.gz"
    - "build/tokenbalance-linux-arm64.tar.gz"
    - "build/tokenbalance-linux-alpine.tar.gz"
    - "build/tokenbalance-windows-x64.zip"
    - "build/tokenbalance-windows-x32.zip"
  skip_cleanup: true

before_script:
  - make deps

script:
  - make install
  - make test
  - make coverage

after_success:
  - travis_wait 30 docker pull karalabe/xgo-latest
  - make release

after_deploy:
  - make publish